name = "covers-cart-online-backend"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "covers-cart-online-backend-prod"

[observability]
enabled = true
head_sampling_rate = 1
